 CLASS zcl_test_travel_02  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zcl_test_travel_02  IMPLEMENTATION.
 ENDCLASS.
